# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59eb72018f2e6d3941b7c144a576841d51e5403af04b775cc018af8e71601dea0060cdf03f8976e0abb4cd1bf86449e24a6dea35725a218e95a093323a27fd82

test:
  secret_key_base: 18b3140d11637ba5151d2feb16c4c806bb8cec6cf36249fe0c2a00de1609d13527da9f544776d8fc5eb5df4350c29d389dcda24a2e5dc4ed4eeaac0eaf571db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
